version: "3.4"

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=GoCodeStyle
      - MYSQL_USER=caesar
      - MYSQL_PASSWORD=0000
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/mysql
      - ./etc/5.7/my_setting.cnf:/etc/mysql/conf.d/my_setting.cnf

volumes:
  data:
    name: mysql_db
